'use client'

import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CartContext } from "./_context/CartContext";
import { useState } from "react";
import { Weight } from "lucide-react";

// const inter = Roboto({ subsets: ["latin", Weight: "700"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([])
  return (
    <ClerkProvider>
      <CartContext.Provider value={{cart, setCart}}>
        <html lang="en">
          <body>
            <Header />
            {children}
          </body>
          <Footer />
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
